### ISSUE TITLE
Unable to call methods inside while loop condition statement

### ISSUE THREAD

**Issue by MarcoAmato** [smolang/SemanticObjects#20]
When attempting to call a method inside the condition statement of a while loop, an error is thrown. For example, the following code throws an error:

```
while list.length() < 0 do:
```

As a workaround, I have to save the result of the method call to a variable and then use this variable in the condition statement of the while loop:

```
Int listSize = resultList.length();
while i < listSize do:
```

It would be helpful if methods could be called directly inside the condition statement of a while loop.

**Comment by Edkamb** [comment]
This is done on purpose to separate side-effect-free expressions into their own category to keep the interpreter more simple. Changing this will be a major rewrite and is not planned for the near future.
