### ISSUE TITLE
Error when assigning int to double

### ISSUE THREAD

**Issue by MarcoAmato** [smolang/SemanticObjects#22]
When attempting to assign an int value to a variable of type double, an error is thrown: 
`ERROR: Type Int is not assignable to Double`. 

It would be helpful if SMOL could automatically convert the int value to a double by adding a decimal part set to 0. For example, the int value 1 would be converted to the double value 1.0.

**Comment by rudi** [comment]
I'd slightly prefer an explicit conversion function, e.g. `Float x = float(1);`.  Automatic value conversion can be confusing in larger expressions.  Granted, int-to-float is not as bad as float-to-int or string-to-int..
