### ISSUE TITLE
Print statement not adding new line character

### ISSUE THREAD

**Issue by N-essuno** [smolang/SemanticObjects#26]
Just an enhancement: when using the print statement in SMOL, it does not add a new line character at the end of the output. For example, running the following code:

```
main
    print("Hello,");
    print("world!");
end
```
produces the following output:
`Hello,world!`

However, we expect the output to be:
```
Hello,
world!
```

**Comment by Edkamb** [comment]
I get the second output on my machine, are you on the newest version?

**Comment by N-essuno** [comment]
I noticed that the previous example is wrong: there is no problem for printing strings but it doesn't print the newline for other datatypes (e.g Int and Double)

Running the following code

```
main
    Int a = 32;
    print(a);
    String b = "this_string_variable_should_be_on_newline";
    print(b);
    print("plain_string");
    print(12);
    print("this_plain_string_should_be_on_newline");
end
```
will output:

> 32this_string_variable_should_be_on_newline
> plain_string
> 12this_plain_string_should_be_on_newline

instead of 

> 32
> this_string_variable_should_be_on_newline
> plain_string
> 12
> this_plain_string_should_be_on_newline

**Comment by Edkamb** [comment]
Works for me, can you check you are on the latest version? I remember fixing this in 4af5268

**Comment by N-essuno** [comment]
You're right, I was getting the smol.jar from an outdated local repository.
