### ISSUE TITLE
Influx parameterized queries don't work with parameters taken from Objects created with construct expression

### ISSUE THREAD

**Issue by N-essuno** [smolang/SemanticObjects#31]
Potentially connected to issue #28 .

When launching Influx parameterized queries using as parameters class fields from Objects created using the `construct` expression (getting data from a knowledge graph) it throws an error from InfluxDB.
It seems that the value type passed to InfluxDB while launching the query is somehow not valid. E.g:

In the following code the Influx query is run taking its parameters from the class fields.
Running the following (excerpt from a program):

```
class Pot(String shelfFloor, String groupPosition, String potPosition)

    // Return last moisture detection for the pot
    Double getMoisture()
        Double moisture = 0.0;
        List<Double> influxReturn = null;
        
        influxReturn = access(
            "from(bucket: \"greenhouse_test\")
                |> range(start: -30d)
                |> filter(fn: (r) => r[\"_measurement\"] == \"ast:pot\")
                |> filter(fn: (r) => r[\"_field\"] == \"moisture\")
                |> filter(fn: (r) => r[\"group_position\"] == %1)
                |> filter(fn: (r) => r[\"pot_position\"] == %2)
                |> filter(fn: (r) => r[\"shelf_floor\"] == %3)
                |> keep(columns: [\"_value\"])
                |> last()",
        INFLUXDB("config_local.yml"),
        this.groupPosition,
        this.potPosition,
        this.shelfFloor);

        moisture = influxReturn.get(0);
        return moisture;
    end
end
```

Throws the following error:

```
com.influxdb.exceptions.BadRequestException: error @6:59-6:63: undefined identifier left

error @5:61-5:66: undefined identifier right
        at com.influxdb.internal.AbstractRestClient.responseToError(AbstractRestClient.java:96)
        at com.influxdb.internal.AbstractQueryApi$1.onResponse(AbstractQueryApi.java:211)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

Note that the classes are generated using a method that retrieves data from a knowledge graph:

```
    List<Pot> getPots()
        List<Pot> pots = construct("
        PREFIX ast: <http://www.semanticweb.org/gianl/ontologies/2023/1/sirius-greenhouse#>
        SELECT ?shelfFloor ?groupPosition ?potPosition
        WHERE {
            ?pot rdf:type ast:Pot ;
                ast:hasShelfFloor ?shelfFloor ;
                ast:hasGroupPosition ?groupPosition ;
                ast:hasPotPosition ?potPosition .
        }");
        return pots;
    end
```

After I retrieve the Pots I iterate on them launching the the InfluxDB query (`getMoisture()`):

```
    List<Pot> pots = assetModel.getPots(config);
    Int lengthPots = pots.length();
    while i < lengthPots do
        print(" moisture: ");
        Double moisture = pot.getMoisture();
        print(moisture);
        i = i+1;
    end
```

---

I also tried to simply manually create a new `Pot` and running the `getMoisture()` method above and it works correctly E.g:

```
String groupPosition = "right";
String potPosition = "left";
String shelfFloor = "1";
Pot pot1 = new Pot(shelfFloor, groupPosition, potPosition);
Double moisture = pot1.getMoisture();
print(moisture);
```

 so I suppose the problem is when a `Pot` is created from the `construct` query.

**Comment by N-essuno** [comment]
Update:

The query sent to influxDB is still sending unquoted values for string parameters containing only digits.
In particular this is happening when the parameter's values are retrieved from the asset model, the parameter's values are correctly quoted when passing strings directly initialized in the SMOL program (instead of retrieving objects using the access statement).

In the following code snippet note the difference between the value assigned to shelf_floor

input to `val results = influxDBClient!!.getQueryKotlinApi().query(...)` in the `no.uio.microobject.runtime.Interpreter `class when querying influxDB creating a new Pot with new statement

```
from(bucket: "greenhouse_test")
                |> range(start: -30d)
                |> filter(fn: (r) => r["_measurement"] == "ast:pot")
                |> filter(fn: (r) => r["_field"] == "moisture")
                |> filter(fn: (r) => r["group_position"] == "right")
                |> filter(fn: (r) => r["pot_position"] == "left")
                |> filter(fn: (r) => r["shelf_floor"] == "1")
                |> keep(columns: ["_value"])
                |> last()
```

input to `val results = influxDBClient!!.getQueryKotlinApi().query(...)` in the `no.uio.microobject.runtime.Interpreter` class when querying influxDB creating a Pot from asset model (construct statement)

```
from(bucket: "greenhouse_test")
                |> range(start: -30d)
                |> filter(fn: (r) => r["_measurement"] == "ast:pot")
                |> filter(fn: (r) => r["_field"] == "moisture")
                |> filter(fn: (r) => r["group_position"] == "right")
                |> filter(fn: (r) => r["pot_position"] == "left")
                |> filter(fn: (r) => r["shelf_floor"] == 1)
                |> keep(columns: ["_value"])
                |> last()
```

For some reason the influxDB cloud instance is capable of retrieving the data even if the value for a tag (tags in influxDB are always supposed to be strings) is an integer, whilst the local instance doesn't return any result in this case.

We think that the source of the problem could be the following line in the eval method of the `no.uio.microobject.ast.stmt.ContructStmt` class

`else if(extractedName.matches("\\d+".toRegex()) || extractedName.matches("\\d+\\^\\^http://www.w3.org/2001/XMLSchema#integer".toRegex()))`

In particular we saw that the evaluation of `extractedName.matches("\\d+".toRegex())`  is true when, in the asset model, we have a string datatype containing a digit.

**Comment by rudi** [comment]
> In particular we saw that the evaluation of `extractedName.matches("\\d+".toRegex())` is true when, in the asset model, we have a string datatype containing a digit.

Seems like that should be something like `"^\\d+$".toRegex()`, since otherwise this regex matches any string with one or more digits in the middle?

**Comment by Edkamb** [comment]
See #28
