### ISSUE TITLE
Hidden classes

### ISSUE THREAD

**Issue by Edkamb** [smolang/SemanticObjects#9]
We have `hidden` fields that are skipped during lifting. We should have `hidden` classes whose objects are skipped as well. Syntax:

```
hidden class C(Int D) end
```

A `hidden` class can only have `hidden` subclasses.
Every field of a non-`hidden` class that has a `hidden` type, must be `hidden` as well. 

Two points should be discussed:
- How should `hidden` classes with a non-`hidden` superclass be treated during lifting?
- Should we have `hidden` objects as well? This would mirror the structure of `models` and roughly have the following syntax: `D d = hidden D();`

**Comment by rudi** [comment]
> Should we have hidden objects as well?

No strong opinion on that one, except that it would make the formal semantics of smol semantic lifting slightly more complex.

Concretely, instead of a predicate hidden(C), you'd have to handle the object case as well -- hidden(C(o)) \vee hidden(o)

**Comment by Edkamb** [comment]
The `hidden` modifier for fields is misnamed and not implemented at the master branch.

**Comment by Edkamb** [comment]
We decided to not implement `hidden` for classes:

- For ISSA, it suffices to use it on field level for modeling in many cases, and it messes with the type system and ontology (cf. polymorphic lists where some object/subclasses are hidden, what are the axioms for `prog:List_content`?)
- For ESSA, one can blacklist classes from lifting, like in Anton's work.

Figuring out how such a feature would interact with the type system and axioms would be a possible smaller project.
